//! Compile-time configuration defaults
//!
//! This module includes the merged configuration generated by build.rs.
//! Values come from:
//! 1. Library defaults (always present)
//! 2. User's gvt_config.rs (if GVT_CONFIG_RS env var set at build time)
//!
//! All values can still be overridden at runtime via environment variables.

// Include the merged config generated by build.rs
include!(concat!(env!("OUT_DIR"), "/gvt_merged_config.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_defaults_exist() {
        // Verify all required constants are defined
        let _ = NUM_WORKERS;
        let _ = NUM_LOW_PRIORITY_WORKERS;
        let _ = MAX_GVTHREADS;
        let _ = TIME_SLICE_MS;
        let _ = GRACE_PERIOD_MS;
        let _ = TIMER_INTERVAL_MS;
        let _ = TIMER_MAX_SLEEP_MS;
        let _ = ENABLE_FORCED_PREEMPT;
        let _ = DEBUG_LOGGING;
        let _ = STACK_SIZE;
        let _ = LOCAL_QUEUE_CAPACITY;
        let _ = GLOBAL_QUEUE_CAPACITY;
        let _ = IDLE_SPINS;
        let _ = PARK_TIMEOUT_MS;
    }

    #[test]
    fn test_reasonable_defaults() {
        assert!(NUM_WORKERS >= 1);
        assert!(NUM_WORKERS <= 256);
        assert!(MAX_GVTHREADS >= 1);
        assert!(TIME_SLICE_MS >= 1);
        assert!(STACK_SIZE >= 64 * 1024); // At least 64KB
    }
}